import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProviderWrapper } from '../context/AuthProviderWrapper';
import Footer from './components/Layout/Footer';
import Header from './components/Layout/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Tassky',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full min-w-screen`}
      >
        <AuthProviderWrapper>
          <Header />
          <main className="flex-grow w-full h-full bg-gradient-to-b from-white to-violet-600">
            {/* <main className="flex-grow flex items-center justify-center  w-full h-full bg-gradient-to-b from-white to-violet-600"> */}
            {children}
          </main>
          <Footer />
        </AuthProviderWrapper>
      </body>
    </html>
  );
}
